### 🔍 Comparison: Python List vs NumPy Array

| Feature                         | Python List                               | NumPy Array                                      |
|----------------------------------|--------------------------------------------|--------------------------------------------------|
| **Data type flexibility**        | Can store mixed data types                 | Requires same data type (homogeneous)            |
| **Memory efficiency**            | Less efficient (each item is an object)    | More memory efficient                            |
| **Speed for computation**        | Slower for numeric operations              | Much faster with large data                      |
| **Element-wise operations**      | No (use loops or list comprehension)       | Yes (e.g., `array + 1`, `array * 2`)             |
| **Broadcasting**                 | Not supported                              | Fully supported                                  |
| **Slicing**                      | Supported                                  | Supported                                        |
| **Multi-dimensional support**    | Limited (nested lists)                     | Full support for 2D, 3D, etc.                    |
| **Mathematical functions**       | No (use `math` module or manual loops)     | Built-in functions like `np.sum()`, `np.mean()` |
| **Best use case**                | General-purpose storage                    | Numeric computations and data analysis           |


In [10]:
import numpy as np
# 1. Array Creation
a1 = np.array([1, 2, 3])                     # 1D array
a2 = np.array([[1, 2], [3, 4]])              # 2D array
a3 = np.array([1, 2, 3], ndmin=3)            # Create 3D array using ndmin
print("1D:\n", a1, "\n2D:\n", a2, "\n3D:\n", a3)

1D:
 [1 2 3] 
2D:
 [[1 2]
 [3 4]] 
3D:
 [[[1 2 3]]]


In [11]:
# 2. Array properties
print("Shape:", a2.shape)
print("Size:", a2.size)
print("Data Type:", a2.dtype)
print("Dimensions:", a2.ndim)

Shape: (2, 2)
Size: 4
Data Type: int64
Dimensions: 2


In [7]:
# 3. Creating arrays with functions
print("Zeros:\n", np.zeros((2, 3)))
print("Ones:\n", np.ones((2, 2)))
print("Range:\n", np.arange(0, 10, 2))
print("Linspace:\n", np.linspace(0, 1, 5))

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]]
Range:
 [0 2 4 6 8]
Linspace:
 [0.   0.25 0.5  0.75 1.  ]


In [13]:
# 4.1 Indexing and Slicing
arr = np.array([[10, 20, 30], [40, 50, 60]])
print("Access single element:", arr[1, 2])
print("Slice row 0:", arr[0, :])
print("Slice column 1:", arr[:, 1])
# 4.2 Indexing and Slicing (Multi-dimensional)
arr = np.array([[10, 20, 30], 
                [40, 50, 60], 
                [70, 80, 90]])

print("Original 2D Array:\n", arr)

# Access single element (row 1, col 2)
print("Element at [1,2]:", arr[1, 2])  # Output: 60

# Slice entire row 0
print("Row 0:", arr[0, :])  # Output: [10 20 30]

# Slice entire column 1
print("Column 1:", arr[:, 1])  # Output: [20 50 80]

# Slice sub-matrix: first 2 rows, last 2 columns
print("Sub-matrix (0:2, 1:3):\n", arr[0:2, 1:3])

# Get last row using negative index
print("Last row:", arr[-1])  # Output: [70 80 90]

# Get every second column
print("Every 2nd column:\n", arr[:, ::2])  # Output: columns 0 and 2

# Get a corner 2x2 block
print("Top-left 2x2 block:\n", arr[:2, :2])  # Output: [[10 20], [40 50]]


Access single element: 60
Slice row 0: [10 20 30]
Slice column 1: [20 50]
Original 2D Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Element at [1,2]: 60
Row 0: [10 20 30]
Column 1: [20 50 80]
Sub-matrix (0:2, 1:3):
 [[20 30]
 [50 60]]
Last row: [70 80 90]
Every 2nd column:
 [[10 30]
 [40 60]
 [70 90]]
Top-left 2x2 block:
 [[10 20]
 [40 50]]


In [14]:
# 5. Iteration
print("Iterating over 2D array:")
for row in arr:
    print("Row:", row)
print("Iterating each element:")
for val in np.nditer(arr):
    print(val, end=" ")

Iterating over 2D array:
Row: [10 20 30]
Row: [40 50 60]
Row: [70 80 90]
Iterating each element:
10 20 30 40 50 60 70 80 90 

In [16]:
# 6. Reshape, Flatten, Transpose
reshaped = np.arange(12).reshape(3, 4)
print("\nReshaped to 3x4:\n", reshaped)
print("Flattened:", reshaped.flatten())
print("Transposed:\n", reshaped.T)


Reshaped to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [17]:
# 7. Mathematical operations
print("Add 5:\n", reshaped + 5)
print("Multiply:\n", reshaped * 2)
print("Dot Product:\n", np.dot([1, 2], [3, 4]))

Add 5:
 [[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Multiply:
 [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
Dot Product:
 11


In [18]:
# 8. Aggregation
print("Sum:", reshaped.sum())
print("Mean:", reshaped.mean())
print("Max:", reshaped.max())
print("Std Dev:", reshaped.std())

Sum: 66
Mean: 5.5
Max: 11
Std Dev: 3.452052529534663


In [19]:
# 9. Filtering with conditions
print("Elements > 5:\n", reshaped[reshaped > 5])

Elements > 5:
 [ 6  7  8  9 10 11]


In [20]:
# 10. Stacking and Concatenation
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print("Vertical Stack:\n", np.vstack((a, b)))
print("Horizontal Stack:\n", np.hstack((a, a)))

Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]]
Horizontal Stack:
 [[1 2 1 2]
 [3 4 3 4]]


In [21]:
# 11. Concatenation
x = np.array([[1, 2]])
y = np.array([[3, 4]])
print("Concat along axis 0:\n", np.concatenate((x, y), axis=0))
print("Concat along axis 1:\n", np.concatenate((x.T, y.T), axis=1))

Concat along axis 0:
 [[1 2]
 [3 4]]
Concat along axis 1:
 [[1 3]
 [2 4]]


In [22]:
# 12. Copy vs View
original = np.array([1, 2, 3])
copy = original.copy()
view = original.view()
original[0] = 100
print("Original:", original)
print("Copy (unchanged):", copy)
print("View (linked):", view)

Original: [100   2   3]
Copy (unchanged): [1 2 3]
View (linked): [100   2   3]


In [23]:
# 13. Broadcasting
X = np.array([[1], [2], [3]])
Y = np.array([10, 20, 30])
print("Broadcasting:\n", X + Y)

Broadcasting:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]
